apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of pods you want to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Replace with your custom Nginx image if needed
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf  # Mounting custom nginx.conf if needed
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-map  # Optional if you have a config map
